addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.1")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("com.github.sbt" % "sbt-site"       % "1.5.0")
addSbtPlugin("org.typelevel"  % "sbt-tpolecat"   % "0.5.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
