addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"    % "0.4.1")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"      % "1.3.2")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"   % "0.6.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage" % "1.6.1")
addSbtPlugin("org.foundweekends"         % "sbt-bintray"   % "0.5.4")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.13")
